name: rakuten
version: 0.1.1.1
synopsis: The Rakuten API in Haskell
description: See README at <https://github.com/matsubara0507/rakuten#readme>
maintainer: MATSUBARA Nobutada
author: MATSUBARA Nobutada
copyright: 2017-2018 MATSUBARA Nobutada
license: MIT
github: matsubara0507/rakuten
category: Web

ghc-options: -Wall

dependencies:
  - base >=4.7 && <5
  - aeson >=1.0.2.1 && <1.3
  - bytestring >=0.10.8.1 && <0.11
  - connection >=0.2.7 && <0.3
  - constraints >=0.9.1 && <0.11
  - data-default-class >=0.1.2.0 && <0.2
  - extensible >=0.4.7.2 && <0.4.9
  - http-api-data >=0.3.5 && <0.3.9
  - http-client >=0.5.5.0 && <0.6
  - http-client-tls >=0.3.3.1 && <0.4
  - http-types >=0.9.1 && <0.13
  - lens >=4.15.3 && <5.0
  - req >=0.3.0 && <1.1.0
  - text >=1.2.2.1 && <1.3

library:
  source-dirs: src
  exposed-modules:
    - Rakuten
    - Rakuten.Client
    - Rakuten.Endpoints
    - Rakuten.Endpoints.Ichiba
    - Rakuten.Types
    - Rakuten.Types.Base
    - Rakuten.Types.Class
    - Rakuten.Types.Error
    - Rakuten.Types.Ichiba

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
      - src
    dependencies:
      - servant-server >=0.9.1.1 && <0.14
      - warp >=3.2.11 && <3.3
      - hspec >=2.4.1 && <2.6
