resolver: nightly-2018-07-06

packages:
- .

extra-deps: []
# - aeson-1.4.0.0
# - http-api-data-0.3.8.1
# - extensible-0.4.10
# - servant-0.14.1
# - servant-server-0.14.1
# - http-types-0.12
# - constraints-0.10
# - req-1.2.1

flags: {}

extra-package-dbs: []
