resolver: nightly-2018-05-11

packages:
- .

extra-deps: []
# - http-api-data-0.3.8.1
# - extensible-0.4.8
# - servant-0.13
# - servant-server-0.13
# - http-types-0.12
# - constraints-0.10

flags: {}

extra-package-dbs: []
